version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 827478161993.dkr.ecr.us-west-2.amazonaws.com
      - IMAGE_TAG=sha-$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - echo "Image tag is $IMAGE_TAG"
      - ECR_IMAGE=827478161993.dkr.ecr.us-west-2.amazonaws.com/devops-g4-service-c:$IMAGE_TAG

  build:
    commands:
      - echo "Building service-c image..."
      - docker build -t devops-g4-service-c:$IMAGE_TAG -f services/service-c/Dockerfile .
      - docker tag devops-g4-service-c:$IMAGE_TAG $ECR_IMAGE

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push $ECR_IMAGE
      - echo "Writing imagedefinitions.json..."
      - printf '[{"name":"service-c","imageUri":"%s"}]' $ECR_IMAGE > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
