services:

  service-a:
    build:
      context: .
      dockerfile: services/service-a/Dockerfile
    container_name: service-a
    ports:
      - "3001:3001"
    environment:
      SERVICE_B_URL: http://service-b:3002
      SERVICE_C_URL: http://service-c:3003
      PORT: 3001
    depends_on:
      - service-b
      - service-c

  service-b:
    build:
      context: .
      dockerfile: services/service-b/Dockerfile
    container_name: service-b
    ports:
      - "3002:3002"
    environment:
      SERVICE_C_URL: http://service-c:3003
      PORT: 3002

  service-c:
    build:
      context: .
      dockerfile: services/service-c/Dockerfile
    container_name: service-c
    ports:
      - "3003:3003"
    environment:
      SERVICE_A_URL: http://service-a:3001
      PORT: 3003